### ISSUE TITLE
TaxFreeAmount 입력이 불가능합니다

### ISSUE THREAD

**Issue by jjang16** [tosspayments/payment-sdk-android#5]
예상 : PaymentWidget.requestPayment 에서 taxFreeAmount parameter 입력 가능
현실 : 그러한 인자값 입력 불가능
라이브러리 버전 : 0.1.1 (Documentation 에 기재된 버전)

https://docs.tosspayments.com/reference/widget-android

Documentation 의 requestPayment 에선 taxFreeAmount를 설정할 수 있게끔 기재되어있습니다.
```
  requestPayment(paymentResultLauncher: ActivityResultLauncher<Intent>,
      orderId: String, 
      orderName: String, 
      customerEmail: String?, 
      customerName: String?,
      taxFreeAmount: Number?
  )
```
하지만 0.1.1 Release 에서 그러한 호출 인터페이스가 발견되지 않습니다.
면세금액을 지정하는 것이 토스페이먼츠의 Spec 에서 사라진 것일까요? 아니면 아직 구현되지 않은 것일까요?

**Comment by kangdromeda** [comment]
안녕하세요 @jjang16 님.

말씀하신 메서드는 0.1.6 버전부터 아래의 메서드로 교체되었습니다.

`fun requestPayment(
        paymentInfo: PaymentMethod.PaymentInfo,
        paymentCallback: PaymentCallback
    )`

상세 내용은 아래의 문서를 확인해주시기 바랍니다.
  
https://docs.tosspayments.com/reference/widget-android#requestpayment

감사합니다.
